### ISSUE TITLE
terminal reboot prevents you from entering the facility

### ISSUE THREAD

**Issue by lxative** [darmuh/ghostCodes#11]
![image](https://github.com/darmuh/ghostCodes/assets/149924874/d97a956e-0ff6-490a-9485-d2a04b5b6458)
using the reboot command prevents you from entering the building until the reboot finishes and throws this error

**Comment by darmuh** [comment]
oh no! That is not good, I'll have to look into this and maybe find an alternative way to disable the terminal.

**Comment by darmuh** [comment]
pushed a hotfix for this issue via update 2.0.5. Thanks again for the report
