### ISSUE TITLE
[Suggestion] Add option to make mod randomly open and/or close ship door

### ISSUE THREAD

**Issue by haroelim** [darmuh/ghostCodes#13]
I was wondering if it would be possible to make the mod mess with the ship door, too. This was actually suggested by one of my friends that often stays on the ship, they think it would add a bit more horror to staying on the ship.

**Comment by darmuh** [comment]
This feature should already be present in the config section "Ship Stuff" unless I'm misunderstanding your suggestion. Or if there's something else you think the doors should do that they don't currently do with those settings enabled please feel free to let me know 👍 

![image](https://github.com/user-attachments/assets/2bbd3b0b-ac9a-4748-a7b1-bf8f918a84db)
