### ISSUE TITLE
[Suggestion] V55 Cruiser 

### ISSUE THREAD

**Issue by dog199200** [darmuh/ghostCodes#14]
It would be interesting to have the ghost be able to affect the cruiser. Some ideas:

* Open the doors randomly (driver, passenger, and the sliding door)
* Change Driving Mode (Random Switch between Park, Drive, and Reverse)
* Turn on/off wipers
* Turn on/off ignition

etc

**Comment by darmuh** [comment]
definitely like the way you're thinking and will work on throwing some ghostcode interactions for the cruiser together in a future update 😁

**Comment by darmuh** [comment]
Hi, thanks again for the suggestions! I added some cruiser interactions as part of 2.5.0 I hope you find some time to try them out!
