### ISSUE TITLE
Mod Networking disabled does not allow for host-only use. 

### ISSUE THREAD

**Issue by Urusovite41** [darmuh/ghostCodes#15]
Hi, 

For some reason, disabling the networking option does not fix the mod to where only the host requires it. Also, Thunderstore lists the mod as deprecated now too for some reason. Anyway, I really enjoy this mod with randoms and was trying to put this on your radar. 

Thank you.

**Comment by darmuh** [comment]
This issue should be fixed in 2.5.0, if you experience any further issues please post under a new issue
