### ISSUE TITLE
Signal translator

### ISSUE THREAD

**Issue by Canatopher** [darmuh/ghostCodes#2]
Currently the signal translator being used only seems to feature a single message, that being a single asterisk and nothing else.
There should be config options associated with this feature, such as disabling it entirely, adjusting the chances of it occurring with a code, or even providing a list of our own random messages.
Could this be adjusted accordingly? Thanks!

**Comment by darmuh** [comment]
Yeah this is a feature I have planned to be much more configurable. For now the random messages have just been a placeholder for something else, kind of like the ideas you have

**Comment by darmuh** [comment]
working on putting out a patch for this today or tomorrow

**Comment by darmuh** [comment]
new config options in 1.5.1

![image](https://github.com/darmuh/ghostCodes/assets/152580271/012eeb1d-dc88-4885-a732-5a03e2d7f546)
