### ISSUE TITLE
Maximum duration on rapidfire?

### ISSUE THREAD

**Issue by AimlessRex** [darmuh/ghostCodes#3]
Is there a possibility there will be a option for a maximum duration on "Rapid Fire" after reaching max insanity, and then possibly having it go on a cool-down where it cannot trigger again even when at max insanity for a period of time?

**Comment by darmuh** [comment]
I could maybe implement this as a feature later. Current plan for future patch is to have something similar for combatting ghostCodes but it requires an aware terminal operator. I figure with that I can also add a configuration option that allows for a "maximum duration" on rapidFire. I think this maximum duration configuration option will be off by default though, as I think the whole point of rapidFire is kind of like the facility is telling you to GET OUT :)

**Comment by darmuh** [comment]
Implemented this feature request in the latest update (2.0.0). 

See below from updated readme:
- If [rapidFireCooldown] is enabled, codes will stop on a short cooldown when codes have been running for [rapidFireMaxHours].
