### ISSUE TITLE
[Question] How do you choose which mode for the mod to use?

### ISSUE THREAD

**Issue by haroelim** [darmuh/ghostCodes#5]
I currently see the option "ghostGirlEnhanced" mode, which is described as "will replace insanity & normal ghost codes modes"

If we have ghostGirlEnhanced mode disabled, how do we choose between the insanity & normal mode?

Furthermore, the config file says the GGEbypassList is a "Comma-Seperated list of moons Ghost Girl Enhanced mode will be bypassed for another mode". Which mode does it choose?

(or am I misunderstanding the insanity and normal modes?)

**Comment by darmuh** [comment]
So to explain the config options a little more clearly, these 4 options can change the mod's behavior drastically.

> ghostGirlEnhanced = codes are run when a ghost girl is haunting someone
> 
> gcInsanityMode = codes are run depending on group total sanity levels
> 
> gcRandomIntervals = when ghostGirlEnhanced mode is not active, determines which set of interval config options to use (random if this is enabled or set if this is disabled)
> 
> GGEbypass = when ghostgirlenhanced is enabled, will fall back on the other possible modes as if ghostGirlEnhanced is disabled
> 

so with the above configuration options you could have many different outcomes. Some examples below:

> ghostGirlEnhanced - enabled
> gcInsanityMode - enabled
> gcRandomIntervals - enabled
> GGEbypass - enabled 

The above would likely be the default config setting. In this, ghostGirlEnhanced is the primary mode and on moons where she can spawn, codes will only be sent when she is haunting. On Moons listed in the "GGEbypasslist" config option, codes will be ran using Insanity Mode and using the random intervals config options.

> ghostGirlEnhanced - enabled
> gcInsanityMode - disabled
> gcRandomIntervals - disabled
> GGEbypass - enabled 

In this configuration setup above, again ghostGirlEnhanced is the primary mode and on moons where she can spawn codes will only be sent when she is haunting. However this time on moons listed in the GGEbypasslist codes will be ran without the insanity mode and using the set interval configuration option.

> ghostGirlEnhanced - enabled
> gcInsanityMode - enabled
> gcRandomIntervals - disabled
> GGEbypass - enabled 

Last example, same as the above with GGE being the primary mode but this time on moons listed in the GGEbypasslist codes will be ran WITH the insanity mode and using the set interval configuration option.

I understand it's a bit confusing, i'm gonna try to figure out how to explain it better in the config file. The confusion mostly comes from the fact that both Insanity Mode and ghostGirl enhanced mode were later additions.

**Comment by darmuh** [comment]
So basically the three "modes" is following this logic tree:

```
Is ghostGirlEnhanced enabled? 
|_  YES = ghostGirlEnhanced Mode 
    |_  is GGEbypass enabled and moon listed in GGEbypasslist?
        |_  YES = Is gcInsanityMode enabled?
            |_  YES = Insanity Mode
                |_  Is gcRandomIntervals enabled?
                    |_  YES = Use random intervals
                    |_  NO  = Use set intervals
            |_  NO  = Normal Mode    
                |_  Is gcRandomIntervals enabled?
                    |_  YES = Use random intervals
                    |_  NO  = Use set intervals
        |_ NO = Mod will not do anything further for this round.
|_  NO = Is gcInsanityMode enabled?
    |_  YES = Insanity Mode
        |_  Is gcRandomIntervals enabled?
            |_  YES = Use random intervals
            |_  NO  = Use set intervals
    |_  NO  = Normal Mode    
        |_  Is gcRandomIntervals enabled?
            |_  YES = Use random intervals
            |_  NO  = Use set intervals
```
