### ISSUE TITLE
Host only? Ghost girl Enchanced mode

### ISSUE THREAD

**Issue by Th3GamingDonkey** [darmuh/ghostCodes#7]
![image](https://github.com/darmuh/ghostCodes/assets/160597650/ecfbd7cf-ef8d-442c-9158-c7ee9fd31662)

I'm confused, so if I want to troll my friends, I need to make them all download this mod if I also want to have Ghost girl Enchanced Mode?

**Comment by darmuh** [comment]
Yes. The ghost girl enhancements can not be synced between all players without networking.
