### ISSUE TITLE
Error during start of round?

### ISSUE THREAD

**Issue by BakaTekku** [darmuh/ghostCodes#8]
I was on Vow 
Line 7224 - Happened right after a full team wipe.
Line 7902 - and again after getting fired and the start of a new round.
[LogOutput.log](https://github.com/darmuh/ghostCodes/files/14366428/LogOutput.log)

**Comment by darmuh** [comment]
hoping to fix this in my upcoming rework for this mod

**Comment by darmuh** [comment]
finally put out the rework. This update should, in theory, fix the errors you were experiencing.

I'm going to close this for now, please feel free to let me know if you experience any issues with the new update 👍
