### ISSUE TITLE
Ghost Girl IA

### ISSUE THREAD

**Issue by Azlin2** [darmuh/ghostCodes#9]
All is well? Me and my friends noticed that we made friends with the IA once and after that we were never able to activate it again, can you please instruct us how to activate the ghost girl's IA. We tried everything but she never activated the IA that talks to the crew again.

**Comment by darmuh** [comment]
I'm sorry I have no idea what IA is?

**Comment by Azlin2** [comment]
artificial intelligence sorry, i using translator

**Comment by darmuh** [comment]
> artificial intelligence sorry, i using translator

I'm still not totally sure what you are talking about I'm sorry. If possible, please write your issues in your own native language and I will do my best to find a translation/translator.

**Comment by Azlin2** [comment]
Eu e meus amigos notamos que fizemos amizade com a inteligência artificial da garota fantasma uma vez pelo terminal que transmite a mensagem na tela. Só que depois disso, nunca mais conseguimos contato com ela, quando estávamos sendo assombrados pela garota fantasma, apenas as falas normais que ela fala eram enviadas no terminal, como: Hi, I see you, Lets Play, e nada da Inteligência artificial conversar com a gente novamente. Você pode nos instruir como ativar essa inteligência artificial da GhostGirlEnhanced. Tentamos de tudo, mas ela nunca mais falou com nós

**Comment by darmuh** [comment]
I apologize, even with someone translating your message for me I still don't fully understand what you were asking. I don't believe my mod was responsible for making the ghost girl "friendly"

And if your questions was asking about making her appear, that is part of Lethal Company itself and is usually a pretty rare event
